export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export const words = [
  // "CRY",
  // "FOSSIL",
  // "POCKET",
  // "MILE",
  // "JELLY",
  // "WELL",
  // "CURTAIN",
  // "PASSIVE",
  // "ABUNDANT",
  // "VISUAL",
  // "PEAK",
  // "MOTHER",
  // "DEADLY",
  // "FLAT",
  // "DAIRY",
  // "INJECT",
  // "GLOOM",
  // "LARGE",
  // "SYMBOL",
  // "MARS",
  // "ANGLE",
  // "COMPLAIN",
  // "TIRED",
  // "BREED",
  // "DATE",
  // "COURTESY",
  // "TRACE",
  // "TROUBLE",
  // "LITIGATION",
  // "SATISFACTION",
  // "PREDATOR",
  // "COMPENSATION",
  // "PRESCRIPTION",
  // "THRESHOLD",
  "JS",
  "PC",
  "CPU",
  "CSS",
  "VUE",
  "NET",
  "WWW",
  "WEB",
  "PHP",
  "JSX",
  "JSP",
  "ASP",
  "MIT",
  "C++",
  "IBM",
  "HTML",
  "CODE",
  "ISEC",
  "JSON",
  "TECH",
  "JAVA",
  "REACT",
  "EMBER",
  "APPLE",
  "LINUX",
  "POSIX",
  "BASIC",
  "SVELTE",
  "SCRIPT",
  "ANGULAR",
  "AWESOME",
  "PROGRAM",
  "BACKBONE",
  "INTERNET",
  "SOFTWARE",
  "ROBOTICS",
  "ASSEMBLY",
  "LANGUAGE",
  "COMPUTER",
  "BOOTSTRAP",
  "MICROSOFT",
  "JAVASCRIPT",
  "CYBERSPACE",
  "CYBERNETICS",
  "PROGRAMMING",
  "COMPILATION",
  "INSTRUCTION",
  "ENGINEERING",
  "TRANSPILATION",
  "INTERPRETATION",
];

export const TIMER_EASY = 200;
export const BOARD_EASY = 10;
export const WORDS_EASY = 6;

export const TIMER_MEDIUM = 175;
export const BOARD_MEDIUM = 15;
export const WORDS_MEDIUM = 8;

export const TIMER_HARD = 150;
export const BOARD_HARD = 20;
export const WORDS_HARD = 10;
